from yacs.config import CfgNode as CN

C = CN()
C.RAND_SEED = 2020
C.OUTPUT_PATH = 'output/naive_classify/temp'
C.TRAIN_SPLIT = 'train'
C.EVAL_SPLIT = 'val'

# config for model
C.MODEL = CN()
C.MODEL.LOAD_WEIGHTS = ''
C.MODEL.DEVICE = 'cuda'
C.MODEL.BACKBONE_FEATS = [4]
C.MODEL.FC_DIMS = [512]

# config for training
C.TRAIN = CN()
C.TRAIN.TUNE_BACKBONE = False
C.TRAIN.BATCH_SIZE = 64
C.TRAIN.MAX_EPOCH = 75
C.TRAIN.CHECKPOINT_EVERY_EPOCH = 15
C.TRAIN.EVAL_EVERY_EPOCH = 1

C.TRAIN.INIT_LR = 0.0001
C.TRAIN.LR_DECAY_EPOCH = 50
C.TRAIN.LR_DECAY_GAMMA = 0.1
C.TRAIN.WEIGHT_DECAY = 1e-4
C.TRAIN.LOSS_REWEIGHT = True

# settings for Adam
C.TRAIN.ADAM = CN()
C.TRAIN.ADAM.ALPHA = 0.8
C.TRAIN.ADAM.BETA = 0.999
C.TRAIN.ADAM.EPSILON = 1e-8



